---
abstract: 'HTTP Basic and Digest authentication'
author:
  - 'Updated to current name space and currently maintained'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::Exception: 0
  Test::MockObject: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Authentication-Credential-HTTP
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Plugin::Authentication: 0.10005
  Catalyst::Runtime: 0
  Class::Accessor::Fast: 0
  Data::UUID: 0.11
  String::Escape: 0
  URI::Escape: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://dev.catalyst.perl.org/repos/Catalyst/Catalyst-Authentication-Credential-HTTP
version: 1.015
